// Figma is the reference: its results are stored as committed baselines (numbers and names only,
// no screenshots), and our app's results are compared against them measurement by measurement.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { Experiment, Result } from './lab';

const baselineDirectory = path.join(import.meta.dirname, 'baselines/figma');
// The app's latest comparison per experiment (numbers only, committed with the summary).
const comparisonDirectory = path.join(import.meta.dirname, 'baselines/app-comparison');
const summaryPath = path.join(import.meta.dirname, '../../docs/research/interaction-parity.md');

export interface Baseline {
	experiment: string;
	question: string;
	recordedAt: string;
	results: Result[];
}

export interface ComparisonRow {
	key: string;
	figma: string | null;
	app: string | null;
	matches: boolean;
}

export function baselinePath(name: string): string {
	return path.join(baselineDirectory, `${name}.json`);
}

export function writeBaseline(experiment: Experiment, results: Result[]): void {
	mkdirSync(baselineDirectory, { recursive: true });
	const baseline: Baseline = {
		experiment: experiment.name,
		question: experiment.question,
		recordedAt: new Date().toISOString(),
		results
	};
	writeFileSync(baselinePath(experiment.name), `${JSON.stringify(baseline, null, '\t')}\n`);
}

export function readBaseline(name: string): Baseline | null {
	const file = baselinePath(name);
	if (!existsSync(file)) return null;
	const baseline: Baseline = JSON.parse(readFileSync(file, 'utf8'));
	return baseline;
}

/** Every measurement from either side, in baseline order, then app-only ones. */
export function compareResults(figma: Result[], app: Result[]): ComparisonRow[] {
	const appValues = new Map(app.map((result) => [result.key, result.value]));
	const rows: ComparisonRow[] = figma.map((result) => {
		const appValue = valueOrNull(appValues, result.key);
		return {
			key: result.key,
			figma: result.value,
			app: appValue,
			matches: appValue === result.value
		};
	});
	const figmaKeys = new Set(figma.map((result) => result.key));
	for (const result of app) {
		if (figmaKeys.has(result.key)) continue;
		rows.push({ key: result.key, figma: null, app: result.value, matches: false });
	}
	return rows;
}

function valueOrNull(values: Map<string, string>, key: string): string | null {
	const value = values.get(key);
	if (value === undefined) return null;
	return value;
}

export function renderComparison(
	experiment: Experiment,
	baseline: Baseline,
	rows: ComparisonRow[],
	appError: string | null
): string {
	const mismatches = rows.filter((row) => !row.matches).length;
	const lines = [
		`# ${experiment.name}: Figma vs app`,
		'',
		experiment.question,
		'',
		`Figma baseline recorded ${baseline.recordedAt}. ${rows.length - mismatches}/${rows.length} measurements match.`,
		'',
		'Traces and screenshots: [figma/report.md](figma/report.md), [app/report.md](app/report.md).',
		''
	];
	if (appError) lines.push(`**App run failed:** ${appError}`, '');
	lines.push('| | Measurement | Figma | App |', '| --- | --- | --- | --- |');
	for (const row of rows) {
		let mark = '✗';
		if (row.matches) mark = '✓';
		lines.push(`| ${mark} | ${escapeCell(row.key)} | ${cell(row.figma)} | ${cell(row.app)} |`);
	}
	lines.push('');
	return lines.join('\n');
}

function cell(value: string | null): string {
	if (value === null) return '—';
	return escapeCell(value);
}

function escapeCell(text: string): string {
	return text.replace(/\|/g, '\\|');
}

interface StoredComparison {
	experiment: string;
	comparedAt: string;
	error: string | null;
	rows: ComparisonRow[];
}

export function writeComparisonRows(
	name: string,
	rows: ComparisonRow[],
	error: string | null
): void {
	mkdirSync(comparisonDirectory, { recursive: true });
	const stored: StoredComparison = {
		experiment: name,
		comparedAt: new Date().toISOString(),
		error,
		rows
	};
	writeFileSync(
		path.join(comparisonDirectory, `${name}.json`),
		`${JSON.stringify(stored, null, '\t')}\n`
	);
}

function readComparisonRows(name: string): StoredComparison | null {
	const file = path.join(comparisonDirectory, `${name}.json`);
	if (!existsSync(file)) return null;
	const stored: StoredComparison = JSON.parse(readFileSync(file, 'utf8'));
	return stored;
}

/** docs/research/interaction-parity.md: every experiment's latest Figma-vs-app differences. */
export function writeParitySummary(experiments: Experiment[]): void {
	const lines = [
		'# Interaction parity: Figma vs app',
		'',
		'Generated by `bun run interactions run|check`; do not edit. Each experiment drives Figma and',
		'the app with the same CDP input (`scripts/interaction-lab/experiments/`). Figma values are the',
		'committed baselines; re-run an experiment to refresh its section.',
		''
	];
	let total = 0;
	let matching = 0;
	const sections: string[] = [];
	for (const experiment of experiments) {
		const stored = readComparisonRows(experiment.name);
		if (!stored) {
			sections.push(`## ${experiment.name}`, '', '_Not compared yet._', '');
			continue;
		}
		total += stored.rows.length;
		const matches = stored.rows.filter((row) => row.matches);
		matching += matches.length;
		sections.push(...renderSection(experiment, stored, matches.length));
	}
	lines.push(`**${matching}/${total} measurements match.**`, '', ...sections);
	writeFileSync(summaryPath, lines.join('\n'));
}

function renderSection(
	experiment: Experiment,
	stored: StoredComparison,
	matches: number
): string[] {
	const lines = [
		`## ${experiment.name} (${matches}/${stored.rows.length})`,
		'',
		experiment.question,
		'',
		`Compared ${stored.comparedAt}.`,
		''
	];
	if (stored.error) lines.push(`**App run failed:** ${stored.error}`, '');
	const differences = stored.rows.filter((row) => !row.matches);
	if (differences.length === 0) {
		lines.push('All measurements match.', '');
		return lines;
	}
	lines.push('| Measurement | Figma | App |', '| --- | --- | --- |');
	for (const row of differences) {
		lines.push(`| ${escapeCell(row.key)} | ${cell(row.figma)} | ${cell(row.app)} |`);
	}
	lines.push('');
	return lines;
}
