// Performance experiments are measurements, not parity checks: both targets' timings go side by
// side with the app/Figma ratio, in docs/research/performance-parity.md (numbers only).

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { Experiment, Result } from './lab';

const summaryPath = path.join(import.meta.dirname, '../../docs/research/performance-parity.md');

interface StoredRun {
	startedAt: string;
	results: Result[];
	error: string | null;
}

/** The latest run of an experiment on a target, from its samples.json, if any. */
export function readRun(outputRoot: string, name: string, target: string): StoredRun | null {
	const file = path.join(outputRoot, name, target, 'samples.json');
	if (!existsSync(file)) return null;
	const stored: StoredRun = JSON.parse(readFileSync(file, 'utf8'));
	return stored;
}

export function writePerformanceSummary(
	outputRoot: string,
	experiments: Experiment[],
	environment: string
): void {
	const lines = [
		'# Performance: Figma vs app',
		'',
		'Generated by `bun run interactions perf`; do not edit. Both targets run the same steps under',
		'the same conditions; ratio > 1 means the app is slower.',
		'',
		`Environment of the latest run: ${environment}`,
		''
	];
	for (const experiment of experiments) {
		lines.push(...renderExperiment(outputRoot, experiment));
	}
	writeFileSync(summaryPath, lines.join('\n'));
}

function renderExperiment(outputRoot: string, experiment: Experiment): string[] {
	const figma = readRun(outputRoot, experiment.name, 'figma');
	const app = readRun(outputRoot, experiment.name, 'app');
	const lines = [`## ${experiment.name}`, '', experiment.question, ''];
	if (figma) lines.push(`Figma run ${figma.startedAt}${failure(figma)}.`);
	if (app) lines.push(`App run ${app.startedAt}${failure(app)}.`);
	lines.push('', '| Measurement | Figma | App | App / Figma |', '| --- | --- | --- | --- |');
	const figmaValues = valuesOf(figma);
	const appValues = valuesOf(app);
	const keys = [...new Set([...figmaValues.keys(), ...appValues.keys()])];
	for (const key of keys) {
		const figmaValue = figmaValues.get(key);
		const appValue = appValues.get(key);
		lines.push(
			`| ${key} | ${show(figmaValue)} | ${show(appValue)} | ${ratio(figmaValue, appValue)} |`
		);
	}
	lines.push('');
	return lines;
}

function failure(run: StoredRun): string {
	if (!run.error) return '';
	return ` (failed: ${run.error})`;
}

function valuesOf(run: StoredRun | null): Map<string, string> {
	if (!run) return new Map();
	return new Map(run.results.map((result) => [result.key, result.value]));
}

function show(value: string | undefined): string {
	if (value === undefined) return '—';
	return value;
}

function ratio(figmaValue: string | undefined, appValue: string | undefined): string {
	const figmaNumber = Number(figmaValue);
	const appNumber = Number(appValue);
	if (!Number.isFinite(figmaNumber) || !Number.isFinite(appNumber)) return '';
	if (figmaNumber === 0) return '';
	return `${(appNumber / figmaNumber).toFixed(2)}×`;
}
