// Generates `packages/plugin-typings` (@neoworks/plugin-typings), the typings a plugin author gets
// for `design`: the declarations of the worker SDK (src/lib/plugins/worker/design.ts and what it
// uses) emitted by tsc, an index that declares the `design` global, and a JSON schema of the
// manifest made from the same zod schema the app validates with.
//
//   bun run plugin-typings           write packages/plugin-typings
//   bun run plugin-typings --check   fail when what is committed is out of date

import {
	cpSync,
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync
} from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { pluginManifestSchema } from '../src/lib/plugins/manifest';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packageDirectory = path.join(root, 'packages', 'plugin-typings');
const ENTRY = 'src/lib/plugins/worker/design.ts';
/** What the generator owns inside the package; the examples and package.json are written by hand. */
const GENERATED = ['types', 'index.d.ts', 'manifest.schema.json'];

const INDEX = `// Generated by scripts/plugin-typings.ts from src/lib/plugins/worker/design.ts. Do not edit.
import type { DesignApi } from './types/lib/plugins/worker/design';

export * from './types/lib/plugins/worker/design';
export type * from './types/lib/plugins/worker/events';
export type * from './types/lib/plugins/worker/namespaces';
export type * from './types/lib/plugins/worker/network';
export type * from './types/lib/plugins/worker/storage';
export type * from './types/lib/plugins/worker/ui';
export type * from './types/lib/plugins/api/types';
export type * from './types/lib/plugins/surface';

declare global {
	/** The capability a plugin is handed: the document, selection, commands, UI and storage. */
	const design: DesignApi;
}
`;

function packageJson(version: string): string {
	return `${JSON.stringify(
		{
			name: '@neoworks/plugin-typings',
			version,
			description:
				'TypeScript typings for the design plugin API (the `design` global) and the manifest schema.',
			types: 'index.d.ts',
			files: ['index.d.ts', 'types', 'manifest.schema.json'],
			license: 'UNLICENSED'
		},
		null,
		'\t'
	)}\n`;
}

function emitDeclarations(outputDirectory: string): void {
	const result = spawnSync(
		'bunx',
		[
			'tsc',
			'--ignoreConfig',
			'--declaration',
			'--emitDeclarationOnly',
			'--skipLibCheck',
			'--outDir',
			outputDirectory,
			'--rootDir',
			'src',
			'--target',
			'ES2022',
			'--module',
			'ESNext',
			'--moduleResolution',
			'bundler',
			'--strict',
			ENTRY
		],
		{ cwd: root, encoding: 'utf8' }
	);
	if (result.status !== 0) {
		throw new Error(`tsc failed:\n${result.stdout}${result.stderr}`);
	}
}

function listFiles(directory: string): string[] {
	const found: string[] = [];
	for (const entry of readdirSync(directory, { withFileTypes: true })) {
		const full = path.join(directory, entry.name);
		if (entry.isDirectory()) found.push(...listFiles(full));
		else found.push(full);
	}
	return found.sort();
}

/** Everything the package holds, by path relative to it. */
export function generate(target: string): Record<string, string> {
	rmSync(target, { recursive: true, force: true });
	mkdirSync(target, { recursive: true });
	emitDeclarations(path.join(target, 'types'));
	writeFileSync(path.join(target, 'index.d.ts'), INDEX);
	const schema = z.toJSONSchema(pluginManifestSchema);
	writeFileSync(
		path.join(target, 'manifest.schema.json'),
		`${JSON.stringify(schema, null, '\t')}\n`
	);
	const existing = path.join(packageDirectory, 'package.json');
	let version = '0.1.0';
	if (existsSync(existing)) version = JSON.parse(readFileSync(existing, 'utf8')).version;
	writeFileSync(path.join(target, 'package.json'), packageJson(version));
	const files: Record<string, string> = {};
	for (const file of listFiles(target))
		files[path.relative(target, file)] = readFileSync(file, 'utf8');
	return files;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	if (process.argv.includes('--check')) {
		const temporary = path.join(root, '.qa', 'plugin-typings-check');
		const fresh = generate(temporary);
		rmSync(temporary, { recursive: true, force: true });
		const committed: Record<string, string> = {};
		for (const file of listFiles(path.join(packageDirectory, 'types'))) {
			committed[path.relative(packageDirectory, file)] = readFileSync(file, 'utf8');
		}
		const stale = Object.keys(fresh).filter(
			(name) => name.startsWith('types/') && fresh[name] !== committed[name]
		);
		if (stale.length > 0) {
			process.stderr.write(
				`plugin typings are out of date: ${stale.join(', ')}. Run bun run plugin-typings.\n`
			);
			process.exit(1);
		}
		process.stdout.write('plugin typings are up to date\n');
	} else {
		const staging = path.join(root, '.qa', 'plugin-typings-staging');
		const files = generate(staging);
		mkdirSync(packageDirectory, { recursive: true });
		for (const name of GENERATED) {
			rmSync(path.join(packageDirectory, name), { recursive: true, force: true });
			cpSync(path.join(staging, name), path.join(packageDirectory, name), { recursive: true });
		}
		if (!existsSync(path.join(packageDirectory, 'package.json'))) {
			cpSync(path.join(staging, 'package.json'), path.join(packageDirectory, 'package.json'));
		}
		rmSync(staging, { recursive: true, force: true });
		process.stdout.write(`wrote ${Object.keys(files).length} files to packages/plugin-typings\n`);
	}
}
