// Generated by scripts/plugin-typings.ts from src/lib/plugins/worker/design.ts. Do not edit.
import type { DesignApi } from './types/lib/plugins/worker/design';

export * from './types/lib/plugins/worker/design';
export type * from './types/lib/plugins/worker/events';
export type * from './types/lib/plugins/worker/namespaces';
export type * from './types/lib/plugins/worker/network';
export type * from './types/lib/plugins/worker/storage';
export type * from './types/lib/plugins/worker/ui';
export type * from './types/lib/plugins/api/types';
export type * from './types/lib/plugins/surface';

declare global {
	/** The capability a plugin is handed: the document, selection, commands, UI and storage. */
	const design: DesignApi;
}
